name: Hello world action
on: [push]
jobs:
  static-code-analysis:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Execute a Bash command
        run: echo "Hello world"
      - name: Check the repo out
        uses: actions/checkout@v4
      - name: List files
        run: echo ${{ github.workspace }}
