name: Release
on: [push]
jobs:
  release:
    name: Release the app
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Set up Corretto JDK 17 for x86_64
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          architecture: x64
      - name: Build the app
        run: mvn -DskipTests package
      - name: List the target directory
        run: ls target/
      - name: Rename the app
        run: mv target/*.jar target/App.jar
      - name: Create a release with the app jar
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/*.jar"
          body: "Release ${{ github.ref }}" 
        
