name: Execute tests
on: [push]
jobs:
  test:
    name: Perform tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Set up Corretto JDK 17 for x86_64
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          architecture: x64
      - name: Execute tests
        run: mvn test
